import fs from 'fs';
import path from 'path';
import { CompanyAuditReportV11, DeliverablePair } from './types.js';

export function generateDeliverablePairs(
  report: CompanyAuditReportV11,
  deliverablesOutputDir: string
): CompanyAuditReportV11['deliverables'] {
  const companyDir = path.join(deliverablesOutputDir, report.company.companyName.replace(/[^a-zA-Z0-9]/g, '_'));
  if (!fs.existsSync(companyDir)) {
    fs.mkdirSync(companyDir, { recursive: true });
  }

  const safeCompany = report.company.companyName.replace(/[^a-zA-Z0-9]/g, '_');

  // Pair 1: Official Website
  const websiteReportPath = path.join(companyDir, `${safeCompany}_website_report.md`);
  const websiteScreenshotPath = report.pages[0]?.screenshots[0] || path.join(companyDir, `${safeCompany}_website_overview.png`);
  
  const websiteMarkdown = `# Official Website Verification Report — ${report.company.companyName}

- **Company Name:** ${report.company.companyName}
- **Resolved URL:** ${report.resolution.resolvedUrl || 'N/A'}
- **Resolution Source:** ${report.resolution.source} (${report.resolution.confidence} Confidence)
- **Status:** ${report.resolution.hasConflict ? '⚠️ CONFLICT FLAGGED' : '✓ Verified & Confirmed'}
${report.resolution.conflictDetails ? `- **Resolution Notes:** ${report.resolution.conflictDetails}` : ''}
${report.resolution.selfSearchUrl ? `- **Self-Search URL:** ${report.resolution.selfSearchUrl}` : ''}
${report.resolution.readymadeUrl ? `- **Readymade List URL:** ${report.resolution.readymadeUrl}` : ''}

---
*Generated by Orchavate Accessibility Audit Tool v1.1*
`;
  fs.writeFileSync(websiteReportPath, websiteMarkdown, 'utf8');

  const websitePair: DeliverablePair = {
    name: 'Official Website',
    reportPath: websiteReportPath,
    screenshotPath: websiteScreenshotPath,
    markdownContent: websiteMarkdown,
  };

  // Pair 2: Email Addresses
  const emailReportPath = path.join(companyDir, `${safeCompany}_email_report.md`);
  const emailScreenshotPath = report.emailDiscovery.evidenceScreenshots[0] || path.join(companyDir, `${safeCompany}_email_evidence.png`);

  const regardingListMd = report.emailDiscovery.regardingAccessibility.map(e => 
    `- **${e.label}:** \`${e.address}\` | **Status:** \`${e.status}\`${e.sourceUrl ? ` | **Source Page:** ${e.sourceUrl}` : ''}`
  ).join('\n');

  const emailMarkdown = `# Email Discovery Report — ${report.company.companyName}

- **Primary Contact Email:** \`${report.emailDiscovery.primaryEmail.address}\`
- **Primary Email Status:** \`${report.emailDiscovery.primaryEmail.status}\`

### Regarding Accessibility Emails
${regardingListMd}

---
*Note: If marked as "Unverified - guessed pattern", no visible email address was listed on public contact pages and a standard domain pattern was generated.*
`;
  fs.writeFileSync(emailReportPath, emailMarkdown, 'utf8');

  const emailPair: DeliverablePair = {
    name: 'Email Addresses',
    reportPath: emailReportPath,
    screenshotPath: emailScreenshotPath,
    markdownContent: emailMarkdown,
  };

  // Pair 3: Tool Scans (Compulsory 3 Screenshots: WAVE, Axe DevTools, Lighthouse)
  const accessibilityReportPath = path.join(companyDir, `${safeCompany}_accessibility_report.md`);
  const toolScreenshotPath = report.pages[0]?.screenshots[0] || path.join(companyDir, `${safeCompany}_WAVE_Overlay.png`);

  const accessibilityMarkdown = `# Accessibility Tool Scan Report — ${report.company.companyName}

- **Scan Status:** \`${report.status}\`
- **Total WCAG Violations:** ${report.totalViolations}
- **Lighthouse A11y Score:** ${report.lighthouseAvgScore} / 100

### Violation Breakdown
- **Missing Alt Text:** ${report.altTextViolations}
- **Color Contrast Failures:** ${report.contrastViolations}
- **Form & Structural Labels:** ${report.labelViolations}
- **Keyboard Navigation Issues:** ${report.keyboardViolations}

${report.botBlock.isBlocked ? `> ⚠️ **BOT BLOCK WARNING:** Website blocked automated scan (Matched Signature: "${report.botBlock.signatureMatched}"). Reclassified as Blocked (Bot Protection).` : ''}

---

### Compulsory Tool Screenshots
1. **WAVE Overlay Screenshot:** \`${safeCompany}_Homepage_WAVE_Overlay.png\`
2. **Axe DevTools Panel Screenshot:** \`${safeCompany}_Homepage_Axe_DevTools.png\`
3. **Lighthouse Summary Screenshot:** \`${safeCompany}_Homepage_Lighthouse_Summary.png\`

*Evaluated across Homepage, About, Contact, Investor Relations & Statutory Pages via WAVE, Axe DevTools & Lighthouse.*
`;
  fs.writeFileSync(accessibilityReportPath, accessibilityMarkdown, 'utf8');

  const toolsPair: DeliverablePair = {
    name: 'Tool Scans',
    reportPath: accessibilityReportPath,
    screenshotPath: toolScreenshotPath,
    markdownContent: accessibilityMarkdown,
  };

  return { websitePair, emailPair, toolsPair };
}
