import fs from 'fs';
import path from 'path';
import { RunReportStats } from './types.js';

export function generateRunReport(
  stats: RunReportStats,
  reportsDir: string,
  priorReport?: RunReportStats
): string {
  const timestampStr = stats.timestamp.replace(/[:.]/g, '-');
  const filename = `RUN_REPORT_${timestampStr}.md`;
  const filepath = path.join(reportsDir, filename);

  if (!fs.existsSync(reportsDir)) {
    fs.mkdirSync(reportsDir, { recursive: true });
  }

  const conflictsRows = stats.conflictsTable.length > 0
    ? stats.conflictsTable.map(c => `| ${c.company} | ${c.selfSearchUrl} | ${c.readymadeUrl} | ${c.status} |`).join('\n')
    : '| None | N/A | N/A | No conflicts flagged |';

  const blockedRows = stats.blockedDomainsTable.length > 0
    ? stats.blockedDomainsTable.map(b => `| ${b.company} | ${b.domain} | ${b.signatureMatched} | ${b.attempts} |`).join('\n')
    : '| None | N/A | N/A | 0 |';

  let diffSection = '';
  if (priorReport) {
    const deltaCompleted = stats.scanStats.completedCount - priorReport.scanStats.completedCount;
    const deltaBlocked = stats.scanStats.blockedCount - priorReport.scanStats.blockedCount;
    const deltaInaccessible = stats.scanStats.inaccessibleCount - priorReport.scanStats.inaccessibleCount;

    diffSection = `
| Metric | Previous run | This run | Change |
|---|---|---|---|
| Completed | ${priorReport.scanStats.completedCount} | ${stats.scanStats.completedCount} | ${deltaCompleted >= 0 ? '+' : ''}${deltaCompleted} |
| Blocked (bot protection) | ${priorReport.scanStats.blockedCount} | ${stats.scanStats.blockedCount} | ${deltaBlocked >= 0 ? '+' : ''}${deltaBlocked} |
| Inaccessible | ${priorReport.scanStats.inaccessibleCount} | ${stats.scanStats.inaccessibleCount} | ${deltaInaccessible >= 0 ? '+' : ''}${deltaInaccessible} |
`;
  } else {
    diffSection = '- No prior run report found to compare against. This is treated as baseline.';
  }

  const manualResearchList = stats.recommendedNextSteps.manualWebsiteResearch.length > 0
    ? stats.recommendedNextSteps.manualWebsiteResearch.map(item => `- ${item}`).join('\n')
    : '- None';

  const noEmailList = stats.recommendedNextSteps.noEmailFound.length > 0
    ? stats.recommendedNextSteps.noEmailFound.map(item => `- ${item}`).join('\n')
    : '- None';

  const unresolvedConflictsList = stats.recommendedNextSteps.unresolvedConflicts.length > 0
    ? stats.recommendedNextSteps.unresolvedConflicts.map(item => `- ${item}`).join('\n')
    : '- None';

  const infraIssuesList = stats.recommendedNextSteps.infraIssues.length > 0
    ? stats.recommendedNextSteps.infraIssues.map(item => `- ${item}`).join('\n')
    : '- None';

  const circuitBreakerContent = stats.circuitBreakerEvents.length > 0
    ? stats.circuitBreakerEvents.map(e => `- ${e}`).join('\n')
    : '- No circuit breaker triggered this run.';

  const throughput = (stats.totalCompanies / (stats.durationSeconds / 3600)).toFixed(1);

  const markdown = `# Run Report — ${stats.timestamp}

*Auto-generated by the accessibility audit tool v1.1 at the end of each run.
This file is written for a human/Claude reviewer to understand the run at a glance — no need to open raw JSON or Excel.*

---

## 1. What this run did

- **Execution Mode:** ${stats.searchMode || 'AUTOMATED_SEARCH'}
- **Search Provider:** ${stats.searchProviderName || 'DuckDuckGo HTML'}
- **Search Attempts:** ${stats.searchAttempts || 0}
- **Average Search Duration:** ${stats.avgSearchTimeMs ? `${stats.avgSearchTimeMs}ms` : '0ms'}
- **Companies processed:** ${stats.totalCompanies}
- **Website resolution:**
  - Resolved via self-search: ${stats.resolutionStats.selfSearchCount}
  - Resolved via readymade fallback: ${stats.resolutionStats.fallbackCount}
  - Conflicts flagged (self-search ≠ readymade): ${stats.resolutionStats.conflictCount}
- **Email discovery:**
  - Verified (found on-page): ${stats.emailStats.verifiedCount}
  - Unverified / guessed pattern: ${stats.emailStats.guessedCount}
  - Not found at all: ${stats.emailStats.notFoundCount}
- **Accessibility scans:**
  - Completed: ${stats.scanStats.completedCount}
  - Blocked (bot protection): ${stats.scanStats.blockedCount}
  - Inaccessible (after retries): ${stats.scanStats.inaccessibleCount}

---

## 2. What went wrong / needed fallback

### Circuit breaker events
${circuitBreakerContent}

### Website conflicts requiring manual review
| Company | Self-search URL | Readymade URL | Status |
|---|---|---|---|
${conflictsRows}

### Domains that blocked scanning repeatedly (after retry)
| Company | Domain | Block signature matched | Attempts |
|---|---|---|---|
${blockedRows}

---

## 3. What improved vs. last run

${diffSection}

---

## 4. Recommended next steps

- **Manual research needed:**
${manualResearchList}
${noEmailList}
${unresolvedConflictsList}

- **Infra/tooling issues worth fixing before next run:**
${infraIssuesList}

---

*Run duration: ${stats.durationSeconds}s | Companies/hour: ${throughput} | Generated: ${stats.timestamp}*
`;

  fs.writeFileSync(filepath, markdown, 'utf8');
  return filepath;
}
